### ISSUE TITLE
User Stories With the Blog System App, I will have two types of users (Guests and Actual Bloggers) who can sign in using their respective credentials, Guest only can select, view, and create a  blog; while an actual blogger can select, view, update, and delete a blog. More updates as my research get refined. 

### ISSUE THREAD

**Issue by dfelleman811** [210823-java-msa-wvu/abraham-diallo-p0#1]
Hi Abraham - please add user stories to your README.md. Clearly list out what features are available to users of type1 and users of type2. Thanks!

**Comment by diallo1980** [comment]
With the Blog System App, I will have two types of users (Guests and Actual Bloggers) who can sign in using their respective credentials, Guest only can select, view, and create a  blog; while an actual blogger can select, view, update, and delete a blog.
More updates as my research get refined.
